# Generated by Django 2.0.6 on 2018-07-24 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import signapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(default='/Users/oh/Desktop/djangoCourse/media/account/identicon.png', upload_to='account/%Y/%m/%d/')),
                ('password', models.CharField(max_length=450)),
                ('info', djongo.models.fields.EmbeddedModelField(blank=True, model_container=signapp.models.InfoTeacher, model_form_class=signapp.models.InfoTeacherForm, null=True)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signapp.Role'),
        ),
    ]
